name: Tests
on:
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**'
      - 'tests/**'

jobs:
  unit_tests:
    # Avoid to run the job twice, once on PR merge and once on the fact that this
    # merge-event is also a push to the master branch
    if: github.event.pull_request.merged == false
    name: Run unit tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'
    # setup-python creates an empty venv and wants to know about
    # requirements.txt, but it does not install any packages from it.
    - name: Install Python packages
      run: python3 -m pip install -r requirements_dev.txt -r requirements.txt build
    - name: Build plaquette
      run: python3 -m build --wheel
    - name: Install plaquette
      run: pip install dist/plaquette*.whl
    - name: Run unit tests
      run: python -m pytest -n auto -m "not slow"


